collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.1961311
  brandStrength: 0.3338659
  rhythmicContrast: 0.8720515
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  lightness: 0.6183819
typography_spectrum: 0.2419355
layout_spectrum: 0
name: seaofclouds
